# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10fEmti5WGxEZIUE67zufZqxy22S1dmMV
"""

import numpy as np
import matplotlib.pyplot as plt

# Datos
años = np.array([1950, 1976, 1992, 2001, 2012, 2019])
poblacion = np.array([2704165, 4613419, 6420792, 8274325, 10059856, 10694075])

def newton_interpolation(x, y, x_value):
    n = len(x)
    coef = np.zeros((n, n))
    coef[:, 0] = y

    for j in range(1, n):
        for i in range(n - j):
            coef[i][j] = (coef[i + 1][j - 1] - coef[i][j - 1]) / (x[i + j] - x[i])

    result = coef[0, 0]
    product = 1

    for j in range(1, n):
        product *= (x_value - x[j - 1])
        result += coef[0, j] * product

    return result

# Predecir la población para el año 2024
año_prediccion = 2024
poblacion_predicha = newton_interpolation(años, poblacion, año_prediccion)

print(f"La población estimada para el año {año_prediccion} es: {poblacion_predicha:.0f}")

# Gráfica
plt.scatter(años, poblacion, color='red', label='Datos conocidos')
plt.plot(año_prediccion, poblacion_predicha, 'bo', label='Predicción para 2024')
plt.title('Interpolación de Newton')
plt.xlabel('Años')
plt.ylabel('Población')
plt.legend()
plt.grid()
plt.show()